ILoveDogs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dogs/', include('dogs.urls'))
]

dogs/urls.py
from django.urls import path

from . import views

app_name = 'dogs'

urlpatterns = [
    path("", views.index, name='index'),
    path("<str:breed>/", views.detail, name = 'detail'),
]

dogs/models.py
from django.db import models

# Create your models here.

dogs/views.py
from django.shortcuts import render
import requests
from django.http import JsonResponse, HttpResponse, Http404
from django.core.exceptions import BadRequest

# Create your views here.
def index(request):
    if request.method == "GET":
        page = int(request.GET.get('page')) if request.GET.get('page') != None else 1
        offset = 10
        start = (page - 1) * offset
        end = page * offset
        catalog = []
        dogs = list(get_dogs())
        if start > len(dogs) or start < 0:
            raise BadRequest("Page doesn't exist")
        for i in dogs[start:end]:
            image = get_random(i)
            catalog.append([i,image])
        previous = None if page==1 else page -1
        next_p = None if page * offset >= len(dogs) else page + 1
        return render(request, "dogs/index.html", {"catalog": catalog,"dogs": dogs ,"previous": previous, "next": next_p})
    else:
        raise BadRequest("Bad method")
    

def detail(request, breed):
    if request.method == "GET":
        images = get_dog(breed)
        if images == "Breed not found (master breed does not exist)":
            raise Http404(	"Breed not found (master breed does not exist)")
        dogs = get_dogs()
        return render(request, "dogs/detail.html", {"breed": breed , "images": images, "dogs": dogs})
    else:
        raise BadRequest("Bad method")
    

def get_dogs():
    url = "https://dog.ceo/api/breeds/list/all"
    response = requests.get(url)
    data = response.json()
    return data["message"]

def get_random(breed):
    url = f"https://dog.ceo/api/breed/{breed}/images/random"
    response = requests.get(url)
    data = response.json()
    return data["message"]

def get_dog(breed):
    url = f'https://dog.ceo/api/breed/{breed}/images/'
    response = requests.get(url)
    data = response.json()
    return data["message"]

dogs/templates/dogs/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dog Catalog</title>
    <style>
      .breed-item {
        display: inline-block;
        margin-right: 20px;
      }
      .home-button {
        margin-top: 20px;
      }

      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        background: #000;
      }

      .header {
        background-color: rgb(255, 255, 255);
        color: #000;
        padding: 10px 20px;
        text-align: center;
        font-family: "Roboto Mono", monospace;
        font-optical-sizing: auto;
        font-style: normal;
        font-size: 24px;
        color: #000;
        text-transform: capitalize;
      }

      .catalog {
        display: grid;
        grid-template-columns: repeat(4, minmax(0, 1fr));
        padding: 0 30px;
      }

      @media screen and (max-width: 1200px) {
        .catalog {
          grid-template-columns: repeat(3, minmax(0, 1fr));
        }
      }
      @media screen and (max-width: 800px) {
        .catalog {
          grid-template-columns: repeat(2, minmax(0, 1fr));
        }
      }

      @media screen and (max-width: 600px) {
        .catalog {
          grid-template-columns: repeat(1, minmax(0, 1fr));
        }
      }

      .void {
        margin: 20px;
      }
      .breed-item {
        border: 2px solid rgb(0, 0, 0);
        border-radius: 20px;
        padding: 10px;
        text-align: center;
        transition: transform 0.3s ease;
        background: #fff;
        width: 100%;
      }

      a {
        text-decoration: none;
        font-family: "Roboto Mono", monospace;
        font-optical-sizing: auto;
        font-style: normal;
        font-size: 24px;
        color: #000;
        text-transform: capitalize;
      }

      a:visited {
        color: #000;
      }

      .breed-item:hover {
        transform: scale(1.05);
      }

      .breed-item img {
        width: 300px;
        height: 300px;
        border-radius: 20px;
      }

      input[type="submit"],
      select {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        background-color: #000000;
        color: #fff;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s ease;
        width: 10rem;
      }

      .home-button{
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        background-color: #000000;
        color: #fff;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s ease;
        width: 10rem;
      }
      input[type="submit"]:hover,
      select:hover {
        background-color: #000000;
      }

      .mainSelect{
        display: flex;
        justify-content: center;
      }
      .inputs {
        display: flex;
        justify-content: space-between;
        max-width: 20%;
        margin: 0 auto;
        padding-top: 2rem;
      }
    </style>
  </head>
  <body>
    <div class="header">
      <h1>{{breed}}</h1>
      <select id="breedSelect" onchange="redirectOnChange()">
        {% for dog in dogs %}
        <option value="{{ dog }}">{{dog}}</option>
        {% endfor %}
      </select>

      <a href="{% url 'dogs:index' %}">
        <button class="home-button">Home</button>
      </a>
    </div>
    <div class="catalog">
      {%for image in images%}
      <div class="void">
        <div class="breed-item"">
          <img src="{{image}}" alt="{{ breed }}" />
        </div>
      </div>

    
      {%endfor%}
    </div>
  </body>
</html>


<script>
    function redirectOnChange() {
      var selectedValue = document.getElementById("breedSelect").value;
      var redirectURL = "http://127.0.0.1:8000/dogs/" + selectedValue;
      window.location.href = redirectURL;
    }
  </script>

dogs/templates/dogs/index.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap"
      rel="stylesheet"
    />
    <title>Dog Catalog</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        background: #000;
      }

      .header {
        background-color: rgb(255, 255, 255);
        color: #000;
        padding: 10px 20px;
        text-align: center;
        font-family: "Roboto Mono", monospace;
        font-optical-sizing: auto;
        font-style: normal;
        font-size: 24px;
        color: #000;
        text-transform: capitalize;
      }

      .catalog {
        display: grid;
        grid-template-columns: repeat(4, minmax(0, 1fr));
      }

      @media screen and (max-width: 1200px) {
        .catalog {
          grid-template-columns: repeat(3, minmax(0, 1fr));
        }
      }
      @media screen and (max-width: 800px) {
        .catalog {
          grid-template-columns: repeat(2, minmax(0, 1fr));
        }
      }

      @media screen and (max-width: 600px) {
        .catalog {
          grid-template-columns: repeat(1, minmax(0, 1fr));
        }
      }

      .void {
        margin: 20px;
      }
      .breed-item {
        border: 2px solid rgb(0, 0, 0);
        border-radius: 20px;
        padding: 10px;
        text-align: center;
        transition: transform 0.3s ease;
        background: #fff;
      }

      a {
        text-decoration: none;
        font-family: "Roboto Mono", monospace;
        font-optical-sizing: auto;
        font-style: normal;
        font-size: 24px;
        color: #000;
        text-transform: capitalize;
      }

      a:visited {
        color: #000;
      }

      .breed-item:hover {
        transform: scale(1.05);
      }

      .breed-item img {
        width: 128px;
        height: 128px;
        border-radius: 20px;
      }

      input[type="submit"],
      select {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        background-color: #000000;
        color: #fff;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s ease;
        width: 10rem;
      }

      input[type="submit"]:hover,
      select:hover {
        background-color: #000000;
      }

      .inputs {
        display: flex;
        justify-content: center;
        max-width: 20%;
        margin: 0 auto;
        padding-top: 2rem;
      }

      .previousBtn {
        margin-right: 20px;
      }
    </style>
  </head>
  <body>
    <div class="header">
      <h1>ILoveDogs</h1>
      <select id="breedSelect" onchange="redirectOnChange()">
        {% for dog in dogs %}
        <option value="{{ dog }}">{{dog}}</option>
        {% endfor %}
      </select>
      <div class="inputs">
        {% if previous %}
        <form class="previousBtn" action="{% url 'dogs:index' %}" method="get">
          <input type="hidden" name="page" value="{{previous}}" />
          <input type="submit" value="Previous Page" />
        </form>
        {% endif %} {% if next %}
        <form action="{% url 'dogs:index' %}" method="get">
          <input type="hidden" name="page" value="{{next}}" />
          <input type="submit" value="Next Page" />
        </form>
        {% endif %}
      </div>
    </div>
    <div class="catalog" id="dogCatalog">
      {% for dog in catalog %}
      <a href="{% url 'dogs:detail' dog.0 %}">
        <div class="void">
          <div class="breed-item" data-breed="{{ dog.0 }}">
            <img src="{{ dog.1 }}" alt="{{ dog.0 }}" />

            <p>{{ dog.0 }}</p>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
  </body>
</html>

<script>
  function redirectOnChange() {
    var selectedValue = document.getElementById("breedSelect").value;
    var redirectURL = "http://127.0.0.1:8000/dogs/" + selectedValue;
    window.location.href = redirectURL;
  }
</script>